### PR TITLE
Support Folia

### PR DESCRIPTION
**Pull request by Euphillya**
I generated a 5k by 5k world with Chunky and a full render with pl3xmap and I found no bugs.

### CODE REVIEW

**Comment by granny** [comment]
Can you see if this is still an issue on folia? https://github.com/BillyGalbreath/Pl3xMap/issues/148

**Comment by Euphillya** [comment]
image
I can see myself, then I'm local and I'm all alone.

**Comment by Euphillya** [comment]
I tried with offline mode to connect bots, and everything seems to work
image

**Review by granny — APPROVED** [review]
LGTM! Could you update the list here to include folia? https://github.com/granny/Pl3xMap/blob/33f05e1ac99964aff64a3543738f390c3a4d2ffe/build.gradle#L159

**Comment by Euphillya** [comment]
good :)

**Pull request merged**
